@startuml
abstract class Exception.ExceptionSistema
abstract class Strategia.MetodosCalculoDistancia
abstract class Strategia.MetodosCalculoEmision
abstract class interprete.SalidaInterprete
annotation java.lang.Override
annotation java.lang.SuppressWarnings
class App.Inves_Final
class CargaDatosExcel.CargaExcelImp
class Exception.NewExceptionCreacionDatos
class Exception.NewExceptionExcel
class Factory.FactoryImp
class Interfase.JPanelElementos
class Interfase.JPanelPrincipals
class MetodosImp.MetodosEjecucionImp
class Strategia.MetodosCalculoDistanciaImp
class Strategia.MetodosCalculoEmisionImp
class Variables.AtributosSistema
class interprete.Contexto
class interprete.SalidaCsv
class interprete.SalidaExcel
class java.io.File
class java.io.FileInputStream
class java.io.FileNotFoundException
class java.io.FileOutputStream
class java.io.IOException
class java.lang.Exception
class java.util.ArrayList
class java.util.HashMap
class javax.swing.JButton
class javax.swing.JFileChooser
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.JOptionPane
class javax.swing.JTextField
class org.apache.poi.ss.usermodel.Cell
class org.apache.poi.ss.usermodel.Row
class org.apache.poi.ss.usermodel.Sheet
class org.apache.poi.ss.usermodel.Workbook
class org.apache.poi.xssf.usermodel.XSSFSheet
class org.apache.poi.xssf.usermodel.XSSFWorkbook
interface CargaDatosExcel.CargaExcel
interface Constantes.Constantes
interface Constantes.ExceptionCrearExcel
interface Constantes.ExceptionLeerExcel
interface Factory.FactoryImplementacion
interface Interfase.ConstantesInterfase
interface MetodosImp.MetodosEjecucion
interface Strategia.MetodosCalculo
Exception.ExceptionSistema --|> java.lang.Exception
Strategia.MetodosCalculoDistancia --|> Strategia.MetodosCalculo
Strategia.MetodosCalculoEmision --|> Strategia.MetodosCalculo
interprete.SalidaInterprete ..> Variables.AtributosSistema
App.Inves_Final ..> Interfase.JPanelPrincipals
CargaDatosExcel.CargaExcelImp ..> Exception.ExceptionSistema
CargaDatosExcel.CargaExcelImp ..> java.lang.Override
CargaDatosExcel.CargaExcelImp ..> Exception.NewExceptionExcel
CargaDatosExcel.CargaExcelImp ..> Variables.AtributosSistema
CargaDatosExcel.CargaExcelImp ..> java.io.File
CargaDatosExcel.CargaExcelImp ..> java.io.FileInputStream
CargaDatosExcel.CargaExcelImp ..> java.io.FileNotFoundException
CargaDatosExcel.CargaExcelImp ..> java.io.FileOutputStream
CargaDatosExcel.CargaExcelImp ..> java.io.IOException
CargaDatosExcel.CargaExcelImp ..> java.util.ArrayList
CargaDatosExcel.CargaExcelImp ..> java.util.HashMap
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.ss.usermodel.Cell
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.ss.usermodel.Row
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.ss.usermodel.Sheet
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.ss.usermodel.Workbook
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.xssf.usermodel.XSSFSheet
CargaDatosExcel.CargaExcelImp ..> org.apache.poi.xssf.usermodel.XSSFWorkbook
CargaDatosExcel.CargaExcelImp --|> CargaDatosExcel.CargaExcel
CargaDatosExcel.CargaExcelImp ..> Constantes.Constantes
Exception.NewExceptionCreacionDatos --|> Exception.ExceptionSistema
Exception.NewExceptionCreacionDatos ..> javax.swing.JOptionPane
Exception.NewExceptionExcel --|> Exception.ExceptionSistema
Exception.NewExceptionExcel ..> Variables.AtributosSistema
Exception.NewExceptionExcel ..> javax.swing.JOptionPane
Exception.NewExceptionExcel ..> Constantes.ExceptionCrearExcel
Exception.NewExceptionExcel ..> Constantes.ExceptionLeerExcel
Factory.FactoryImp ..> java.lang.Override
Factory.FactoryImp ..> CargaDatosExcel.CargaExcel
Factory.FactoryImp --|> Factory.FactoryImplementacion
Factory.FactoryImp ..> Strategia.MetodosCalculo
Interfase.JPanelElementos ..> interprete.SalidaInterprete
Interfase.JPanelElementos ..> java.lang.SuppressWarnings
Interfase.JPanelElementos ..> CargaDatosExcel.CargaExcelImp
Interfase.JPanelElementos ..> Factory.FactoryImp
Interfase.JPanelElementos ..> Strategia.MetodosCalculoDistanciaImp
Interfase.JPanelElementos ..> Strategia.MetodosCalculoEmisionImp
Interfase.JPanelElementos ..> Variables.AtributosSistema
Interfase.JPanelElementos ..> interprete.Contexto
Interfase.JPanelElementos ..> interprete.SalidaCsv
Interfase.JPanelElementos ..> interprete.SalidaExcel
Interfase.JPanelElementos ..> java.io.File
Interfase.JPanelElementos ..> javax.swing.JFileChooser
Interfase.JPanelElementos --|> javax.swing.JFrame
Interfase.JPanelElementos ..> javax.swing.JOptionPane
Interfase.JPanelElementos ..> CargaDatosExcel.CargaExcel
Interfase.JPanelElementos ..> Factory.FactoryImplementacion
Interfase.JPanelElementos --|> Interfase.ConstantesInterfase
Interfase.JPanelPrincipals ..> java.lang.SuppressWarnings
Interfase.JPanelPrincipals --|> javax.swing.JFrame
Interfase.JPanelPrincipals --|> Interfase.ConstantesInterfase
MetodosImp.MetodosEjecucionImp ..> java.lang.Override
MetodosImp.MetodosEjecucionImp ..> Variables.AtributosSistema
MetodosImp.MetodosEjecucionImp ..> java.util.ArrayList
MetodosImp.MetodosEjecucionImp ..> java.util.HashMap
MetodosImp.MetodosEjecucionImp ..> Constantes.Constantes
MetodosImp.MetodosEjecucionImp --|> MetodosImp.MetodosEjecucion
Strategia.MetodosCalculoDistanciaImp --|> Strategia.MetodosCalculoDistancia
Strategia.MetodosCalculoDistanciaImp ..> java.lang.Override
Strategia.MetodosCalculoDistanciaImp ..> Variables.AtributosSistema
Strategia.MetodosCalculoDistanciaImp ..> java.util.ArrayList
Strategia.MetodosCalculoDistanciaImp ..> java.util.HashMap
Strategia.MetodosCalculoDistanciaImp ..> Constantes.Constantes
Strategia.MetodosCalculoEmisionImp --|> Strategia.MetodosCalculoEmision
Strategia.MetodosCalculoEmisionImp ..> java.lang.Override
Strategia.MetodosCalculoEmisionImp ..> java.util.ArrayList
Strategia.MetodosCalculoEmisionImp ..> java.util.HashMap
Variables.AtributosSistema ..> java.util.ArrayList
Variables.AtributosSistema ..> java.util.HashMap
Variables.AtributosSistema ..> Constantes.Constantes
interprete.SalidaCsv --|> interprete.SalidaInterprete
interprete.SalidaCsv ..> java.lang.Override
interprete.SalidaExcel --|> interprete.SalidaInterprete
interprete.SalidaExcel ..> java.lang.Override
interprete.SalidaExcel ..> Variables.AtributosSistema
interprete.SalidaExcel ..> java.io.FileNotFoundException
interprete.SalidaExcel ..> java.io.FileOutputStream
interprete.SalidaExcel ..> java.io.IOException
interprete.SalidaExcel ..> org.apache.poi.ss.usermodel.Row
interprete.SalidaExcel ..> org.apache.poi.ss.usermodel.Sheet
interprete.SalidaExcel ..> org.apache.poi.ss.usermodel.Workbook
interprete.SalidaExcel ..> org.apache.poi.xssf.usermodel.XSSFWorkbook
Factory.FactoryImplementacion ..> CargaDatosExcel.CargaExcel
Factory.FactoryImplementacion ..> Strategia.MetodosCalculo
Interfase.ConstantesInterfase ..> javax.swing.JButton
Interfase.ConstantesInterfase ..> javax.swing.JLabel
Interfase.ConstantesInterfase ..> javax.swing.JTextField
MetodosImp.MetodosEjecucion ..> java.util.ArrayList
MetodosImp.MetodosEjecucion ..> java.util.HashMap
Strategia.MetodosCalculo ..> MetodosImp.MetodosEjecucionImp
Strategia.MetodosCalculo ..> Variables.AtributosSistema
Strategia.MetodosCalculo ..> java.util.ArrayList
Strategia.MetodosCalculo ..> java.util.HashMap
@enduml